-- -----------------------------------------------------------------------------
--
-- ECE 356 Project
-- Data Mining
-- 
-- Walter Alejandro Lam Astudillo	walamast
-- Bruce Nguyen						b34nguye
-- Darius Andrew Wigglesworth		dawiggle
--
-- This file includes various queries used in the data mining
-- analysis of our project.
-- 
